import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ApolloWrapper from '@/api/graphql/apollo'

import './globals.css'
import { GlobalProvider } from '@/context/GlobalContext'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </GlobalProvider>
      </body>
    </html>
  )
}
